[package]
name = "ciso"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

[dependencies.clap]
version = "3.2"
default-features = false
features = [
    "cargo",
    "std",
]

[dependencies.flate2]
version = "1.0"
features = [
    "zlib",
]
